---
apiVersion: v1
kind: Pod
metadata:
  name: pilot-prod-nginx
  labels:
    project: pilot
    environment: production
    tier: frontend
spec:
  containers:
    - image:  nginx
      name:  nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pilot-prod-memcached
  labels:
    project: pilot
    environment: production
    tier: cache
spec:
  containers:
    - name: memcached
      image: memcached
