---
apiVersion: v1
kind: Service
metadata:
  name: pilot-nginx-svc
spec:
  selector:
    project: pilot
    environment: production
    tier: frontend
  type: NodePort
  ports:
  - name:  pilot-nginx-port
    port:  80
    protocol: TCP
