---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-prometheusworker01
  namespace: stack-prometheus-prod
  labels:
    env: production
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-prometheusworker02
  namespace: stack-prometheus-prod
  labels:
    env: production
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-prometheus-master01
  namespace: stack-prometheus-prod
  labels:
    env: production
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
