apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-prometheus
  namespace: monitoring
  labels:
    env: production
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        scrape_interval: 30s
        scrape_timeout: 15s
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
        scheme: http
        metrics_path: /metrics
      - job_name: 'cadvisor'
        scrape_interval: 30s
        scrape_timeout: 15s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                 - kube-system  
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_pod_label_k8s_app]
            action: keep
            regex: cadvisor
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
