---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
  hostPath:
    path: "/Users/bryanalonsoalmeydacontreras/prometheus_storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheusworker
  namespace: monitoring
spec:
  storageClassName: prometheus-storage
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
