---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stack-grafana
  namespace: stack-prometheus-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stack-prometheus-prod
  name: prometheus-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
