---
apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: monitoring
  labels:
    env: production
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 30018
  sessionAffinity: None
