---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.6.0
          command: ["airflow", "scheduler"]
          resources:
            requests:
              cpu: "2"
              memory: 800Mi
            limits:
              cpu: "4"
              memory: 1200Mi
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: apache/airflow:2.6.0
          command: ["airflow", "webserver"]
          resources:
            requests:
              cpu: "2"
              memory: 800Mi
            limits:
              cpu: "4"
              memory: 1200Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
        - name: worker
          image: apache/airflow:2.6.0
          command: ["airflow", "celery", "worker"]
          resources:
            requests:
              cpu: "2"
              memory: 2000Mi
            limits:
              cpu: "4"
              memory: 6000Mi
          
          envFrom:
            - configMapRef:
                name: airflow-config
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31600
  type: NodePort
