---
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: platform-airflow-prod
spec:
  template:
    spec:
      containers:
        - name: airflow-init
          image: apache/airflow:2.6.0
          #command: ["airflow", "db", "init"]
          command:
            - bash
            - -c
            - | 
              airflow db init && \
              airflow users create \
              --username "Airflow Admin" \
              --firstname Admin \
              --lastname User \
              --role Admin \
              --email admin@example.com \
              --password "Starmania_10"
          envFrom:
            - configMapRef:
                name: cfg-scheduler
      restartPolicy: Never
  backoffLimit: 4
