apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: platform-airflow-prod
  labels:
    app: airflow
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6
          resources:
            requests:
              cpu: "250m"
              memory: "800Mi"
            limits:
              cpu: "500m"
              memory: "1600Mi"
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: cfg-redis
