apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      containers:
        - name: redis
          image: redis:6
          resources:
            requests:
              cpu: "2"
              memory: "800Mi"
            limits:
              cpu: "4"
              memory: "1600Mi"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: airflow-redis
  clusterIP: None