---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: platform-airflow-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-cluster-admin
rules:
  - apiGroups: ["*", ""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: platform-airflow-prod
roleRef:
  kind: ClusterRole
  name: airflow-cluster-admin
  apiGroup: rbac.authorization.k8s.io
