apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-postgres
  namespace: platform-gitbucket-prod
  labels:
    app: postgres
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: claro123
  POSTGRES_DB: gitbucket
  TZ: America/Lima
