---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: postgresql
  hostPath:
    path: "/Users/bryanalonsoalmeydacontreras/postgresql_storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: platform-gitbucket-prod
  labels:
    app: pvc-postgres
    env: production
spec:
  storageClassName: postgresql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
