---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  namespace: platform-gitbucket-prod
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres-port
    protocol: TCP
    port: 5432
    targetPort: 5432
