---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  namespace: platform-gitbucket-prod
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres-port
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres-ext
  namespace: platform-gitbucket-prod
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres-port-ext
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32352