apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/bryanalonsoalmeydacontreras/kubernetes/implementaciones/grafana_labs/loki/storage_loki
  storageClassName: loki-hostpath

---

# PVC: reclamo que hace Loki sobre ese volumen
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: loki-hostpath