---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gitbucket
  namespace: platform-gitbucket-prod
  labels:
    app:  gitbucket
spec:
  selector:
    matchLabels:
      app: gitbucket-prd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gitbucket-prd
    spec:
      containers:
      - name:  gitbucket
        image:  gitbucket/gitbucket:latest
        command: ["java"]
        args: ["-jar", "/opt/gitbucket.war"]
        resources:
          requests:
            cpu: "2"
            memory: 800Mi
          limits:
            cpu: "4"
            memory: 1200Mi
        envFrom:
          - configMapRef:
              name: gitbucket-config
        ports:
          - containerPort:  8080
            name:  gitbucket-port
        volumeMounts:
          - name: frontend-repository
            mountPath: "/gitbucket"
      volumes:
        - name: frontend-repository
          persistentVolumeClaim:
            claimName: pvc-gitbucket
      restartPolicy: Always
