---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitbucket
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gitbucket-repository
  hostPath:
    path: "/Users/bryanalonsoalmeydacontreras/gitbucket_repository"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitbucket
  namespace: platform-gitbucket-prod
  labels:
    app: pvc-gitbucket
    env: production
spec:
  storageClassName: gitbucket-repository
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
